### ISSUE TITLE
함수 수정

### ISSUE THREAD

**Issue by smille1018** [Today-s-ToDoList/ToDoList#10]
저희 저번주에 만든 함수에서 수정할 게 있을까요?

**Comment by Dazunx** [comment]
수정하고 싶으신 부분 있으세요?? 좀 더 탄탄히 하면 좋을 거 같긴 해요ㅎㅎ

**Comment by Dazunx** [comment]
제가 조금 수정했습니다. 실행 안되는 건 없지만, 삭제를 하면 출력이 안되어서 완료여부로 검색하는 것은 검색에서 삭제했습니다.

**Comment by Dazunx** [comment]
그리고 ta님께서 실행 할 때 필요한 텍스트 파일도 추가했습니다.

**Comment by Dazunx** [comment]
이슈 닫을게요!!
