### ISSUE TITLE
함수 정의

### ISSUE THREAD

**Issue by smille1018** [Today-s-ToDoList/ToDoList#2]
프로그램을 만들기 위한 함수가 어떤 것들이 있을까요?
CRUD 포함해서 10개 만드는 거 같죠?

**Comment by Dazunx** [comment]
맞는 거 같아요. 그럼 CRUD 제외하고 어떤 함수를 구현해야 할까요?

**Comment by Dazunx** [comment]
CRUD, 파일 로드&저장 함수와 추가로 일정 검색이나, 기한 검색 함수는 어떤 가요?

**Comment by smille1018** [comment]
그렇다면 키워드를 입력하면 그 키워드의 일정을 수행한 날짜를 뜨게 하는 것도 괜찮을 것 같아요!

**Comment by Dazunx** [comment]
저장함수는 파일명을 그 날의 날짜로 하고, 날짜 검색함수에서 open할 파일명에 입력받은 날짜를 넣어서 그 파일의 내용을 불러오는 거 어떤가요?

**Comment by smille1018** [comment]
네! 좋은거 같아요!

**Comment by smille1018** [comment]
지금 그럼,,, 일정추가, 일정수정, 일정삭제, 일정읽기, 파일로 저장(날짜), 날짜검색 까지 나온거죠?

**Comment by Dazunx** [comment]
네네 그럼 날짜검색 함수는 제가 구현할게요!

**Comment by Dazunx** [comment]
일정추가/일정수정 & 파일 불러오기 -> 
일정삭제/일정읽기 & 파일 저장하기 ->

이렇게 나누는 거 어떠세요??

**Comment by smille1018** [comment]
넵! 좋습니다!

**Comment by smille1018** [comment]
일정추가/일정수정 & 파일 불러오기 -> smille1018
일정삭제/일정읽기 & 파일 저장하기 -> Dazunx
이렇게 갑시다!ㅎㅎ

**Comment by Dazunx** [comment]
좋아요 좋아요!

**Comment by smille1018** [comment]
저희가 일정을 적을 때 시간을 적는 옵션도 있으니까 그 시간까지 남은 시간 나타내는 건 어떨까요?

**Comment by smille1018** [comment]
그렇게 되면 현재 시간 알아내는 함수와 남은 시간 알려주는 함수 두개 더 추가하면 좋을 것 같아요!

**Comment by Dazunx** [comment]
오오 좋아요! 근데 생각해보니 파일에 저장하는 것보다 구조체로 저장하는 게 더  좋을 거 같아요!

**Comment by smille1018** [comment]
아 그렇네요! 구조체로 저장합시당!

**Comment by Dazunx** [comment]
일정 하나를 추가할 때 어떤 목록들을 물어볼 건가요?? 예를 들면 일정이름 같은 거요!

**Comment by smille1018** [comment]
일정 이름, 중요도, 시간 정도 물어보면 되지 않을까요?

**Comment by smille1018** [comment]
시간같은 경우는, 몇시까지인지 정해져 있는 경우는 시간을 적어주고 그렇지 않은 경우에는 .을 찍도록 명시해주면 좋을 것 같아요!

**Comment by Dazunx** [comment]
삭제함수는 중요도를 0으로 만들고 일정 불러올 때 중요도가 0일 아닌 것들만 불러오면 어떤 가요???

**Comment by Dazunx** [comment]
> 일정 이름, 중요도, 시간 정도 물어보면 되지 않을까요?

좋아요! 중요도는 1~3 정도로 할까요..??

**Comment by smille1018** [comment]
그러면 중요도는 숫자 몇까지 할까요?

**Comment by smille1018** [comment]
> 

넹! 좋아요!

**Comment by smille1018** [comment]
> > 일정 이름, 중요도, 시간 정도 물어보면 되지 않을까요?
> 
> 좋아요! 중요도는 1~3 정도로 할까요..??

넵! 좋아요

**Comment by Dazunx** [comment]
그럼 정리해보면 CRUD, 파일 저장&로드, 메뉴함수와  날짜 검색함수, 현재 시간 불러오는 함수, 남은 기한 불러오는 함수
이렇게 총 10개 맞죠?

**Comment by smille1018** [comment]
넵넵!!
