### ISSUE TITLE
함수 구현

### ISSUE THREAD

**Issue by Dazunx** [Today-s-ToDoList/ToDoList#4]
저희 함수를 vscode로 구현해서 push 하는 것 맞죠?

**Comment by smille1018** [comment]
네! 맞아요!

**Comment by Dazunx** [comment]
저희가 헤더파일이랑 c파일은 역할 분담을 안 했는데 헤더파일 제가 만들게요!

**Comment by smille1018** [comment]
넵넵! 감사합니다

**Comment by Dazunx** [comment]
근데 현재시간함수랑 기한 출력함수만 헤더파일에 추가해주시면 될 거 같아요!

**Comment by Dazunx** [comment]
아 그리고 loadTodoList함수도 saveTodo함수 구현하면서 제가 구현했습니다.

**Comment by smille1018** [comment]
맡으신 함수 구현부분은 다 끝내신 건가요?

**Comment by Dazunx** [comment]
네네 근데 실행을 아직 안해봐서 에러가 뜰 거 같아요

**Comment by smille1018** [comment]
넵넵! 그러면 저도 얼른 함수 구현한 후 연락 드리겠습니다.

**Comment by Dazunx** [comment]
네 알겠습니다
