### ISSUE TITLE
WIKI 페이지 정리

### ISSUE THREAD

**Issue by smille1018** [Today-s-ToDoList/ToDoList#6]
저희 WIKI 페이지를 어떤 식으로 구현시키면 될까요?
저번 꺼에서 더 추가해서 완성된 WIKI 페이지를 만들면 될까요?

**Comment by smille1018** [comment]
특히 목차에서 클릭하면 각 목록으로 가도록 하고 싶은데 어떻게 하는지 잘 모르겠습니다.
한번 찾아봐 주시면 감사하겠습니다.

**Comment by Dazunx** [comment]
아아 넵 제가 해보고 알려드릴게요

**Comment by smille1018** [comment]
지금 저희 프로젝트 소개에 한줄밖에 안쓰여져 있는데 시간 날때 더 쓰면 좋을 것 같아요!

**Comment by Dazunx** [comment]
넵!!

**Comment by Dazunx** [comment]
제가 wiki페이지 페이지 추가해서 하이퍼링크까지 달았습니다! 각 페이지만 좀 더 자세한 설명이 들어가면 좋을 거 같아요!!

**Comment by smille1018** [comment]
Wiki 페이지에 상세한 설명 좀 더 붙여봤습니다. 확인 부탁드려요!
