### ISSUE TITLE
ToDoList.c

### ISSUE THREAD

**Issue by Dazunx** [Today-s-ToDoList/ToDoList#8]
저도 아직 날짜 검색 함수 아직 구현 안해서 하고 알려드릴게요!

**Comment by smille1018** [comment]
넵!

**Comment by Dazunx** [comment]
날짜 기한 구하는 함수를 실행하면 바로 종료가 되는데 확인 부탁드릴게요!

**Comment by smille1018** [comment]
넵 알겠습니다!

**Comment by Dazunx** [comment]
추가랑 수정 함수에서 띄어쓰기 하거나 한 글자 이상 입력하면 이상해지는데 확인해주실 수 있나요?

**Comment by Dazunx** [comment]
메뉴에서 7번만 완성하면 될 거 같아요!

**Comment by Dazunx** [comment]
좀 어려운 거 같은데 정안되면 빨리 다른 함수로 바꿀 까요?

**Comment by smille1018** [comment]
그게 나을 것 같기도 해요ㅠㅠ

**Comment by Dazunx** [comment]
현재 시간 출력 함수 완성하였고, 기한 계산 함수는 삭제하였습니다.
